# Generated by Django 2.1.3 on 2018-11-28 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('stars', models.CharField(blank=True, max_length=255, null=True)),
                ('review_count', models.CharField(blank=True, max_length=255, null=True)),
                ('categories', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Business',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stars', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('average_stars', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='business.Business')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Tip',
                'managed': False,
            },
        ),
    ]
